import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { ThemeToggle } from "@/components/theme/theme-toggle";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const bodyClasses = `${geistSans.variable} ${geistMono.variable} antialiased`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={bodyClasses} suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider>
            <Theme>
              <div
                className="flex items-center justify-center"
                suppressHydrationWarning
              >
                {children}
              </div>
              <ThemeToggle />
              <Toaster
                position="top-center"
                toastOptions={{
                  success: {
                    style: {
                      background: "#10B981",
                      color: "white",
                      fontWeight: "bold",
                    },
                  },
                  error: {
                    style: {
                      background: "#EF4444",
                      color: "white",
                      fontWeight: "bold",
                    },
                  },
                }}
              />
            </Theme>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
