// MongoDB script to insert car data

let dotenv;
let MongoClient;
let ObjectId;

// Try to load the required modules with error handling
try {
  dotenv = require("dotenv");
  const mongodb = require("mongodb");
  MongoClient = mongodb.MongoClient;
  ObjectId = mongodb.ObjectId;
} catch (error) {
  console.error("\x1b[31mModule loading error:\x1b[0m", error.message);
  console.log("\x1b[33m");
  console.log(
    "Please run the following commands to install required dependencies:"
  );
  console.log("  cd mongodb-scripts");
  console.log("  npm install");
  console.log("\x1b[0m");
  process.exit(1);
}

// Load environment variables
dotenv.config();

async function run() {
  // Connection URI (replace with your actual MongoDB connection string)
  const uri = process.env.MONGODB_URI || "mongodb://localhost:27017";
  const client = new MongoClient(uri);

  try {
    // Connect to the MongoDB server
    await client.connect();
    console.log("\x1b[32mConnected to MongoDB server\x1b[0m");

    // Select the database
    const database = client.db("test");
    const collection = database.collection("cars");

    // Create a new document in the collection - let MongoDB generate _id and use current timestamps
    const result = await collection.insertOne({
      // _id will be automatically generated by MongoDB
      basicInfo: {
        brand: "Tata Motors",
        name: "Tata Nexon",
        variant: "Base",
        variantName: "Nexon Smart",
        carType: "SUV",
        priceExshowroom: 1099990,
        pros: [
          "Futuristic design with interesting details: LED daytime running lamps and tail lamps with animations, 16-inch alloy wheels, and full-LED headlamps. Gives it great road presence.",
          "Has every imaginable feature: panoramic sunroof, front seat ventilation, 360° camera, leatherette upholstery. Feels premium.",
          "Impressive infotainment package: 10.25-inch touchscreen, 10.25-inch driver's display and a brilliant JBL sound system.",
          "Available with petrol and diesel engines, both offered with automatic transmissions.",
        ],
        cons: [
          "Interior storage space is poor. No cupholders, lack of space for phones/wallets hampers everyday usability.",
          "Fit and finish could be improved in the interior. Misaligned panels take away from the experience.",
        ],
      },
      engineTransmission: {
        engineType: "1.5L Turbocharged Revotorq",
        maxPower: "113.31bhp@3750rpm",
        maxTorque: "260Nm@1500-2750rpm",
        displacement: "1497",
        cylinders: "4",
        valvesPerCylinder: "4",
        transmissionType: "Automatic",
        gearbox: "6-Speed AMT",
        driveType: "FWD",
        turboCharger: "Yes",
      },
      fuelPerformance: {
        fuelType: "Diesel",
        mileage: "24.08",
        topSpeed: 180,
        emissionNorm: "BS VI 2.0",
      },
      dimensionsCapacity: {
        length: 3995,
        width: 1804,
        height: 1620,
        wheelBase: 2498,
        groundClearance: 208,
        seatingCapacity: 5,
        doors: 5,
        bootSpace: 382,
      },
      suspensionSteeringBrakes: {
        frontSuspension: "MacPherson Strut suspension",
        rearSuspension: "Rear twist beam",
        steeringType: "Electric",
        steeringColumn: "Tilt & Collapsible",
        turningRadius: 5.1,
        frontBrakeType: "Disc",
        rearBrakeType: "Drum",
        frontWheelSize: 16,
        rearWheelSize: 16,
      },
      comfortConvenience: {
        powerSteering: true,
        airConditioner: true,
        heater: true,
        foldableRearSeat: "60:40 Split",
        parkingSensors: "Front & Rear",
        usbCharger: "",
        adjustableSteering: false,
      },
      interior: {
        tachometer: true,
        gloveBox: true,
        digitalCluster: true,
        digitalClusterSize: 10.3,
        upholstery: "Leatherette",
        additionalInteriorFeatures:
          "2 Spoke Steering Wheel with Illuminated Logo",
      },
      exterior: {
        adjustableHeadlamps: true,
        rearWindowWiper: true,
        rearWindowDefogger: true,
        rearWindowWasher: true,
        integratedAntenna: true,
        ledDRLs: true,
        ledTaillights: true,
        poweredFoldingORVM: true,
        halogenHeadlamps: true,
        fogLights: "Front",
        sunroofType: "Panoramic",
        tyreSize: "215/60 R16",
        tyreType: "Radial",
        additionalExteriorFeatures:
          "Sequential LED DRLs and Taillamp with Welcome/Goodbye Signature, Alloy Wheel with Aero Inserts, Top-mounted Rear Wiper and Washer, Bi Function LED Headlamps",
      },
      safety: {
        antiLockBrakingSystem: true,
        brakeAssist: true,
        centralLocking: true,
        driverAirbag: true,
        childSafetyLocks: true,
        passengerAirbag: true,
        dayNightRearViewMirror: true,
        electronicBrakeforceDistribution: true,
        seatBeltWarning: true,
        tyrePressureMonitoringSystem: true,
        engineImmobilizer: true,
        electronicStabilityControl: true,
        speedSensingAutoDoorLock: true,
        isofixChildSeatMounts: true,
        hillDescentControl: true,
        hillAssist: true,
        airbags: 6,
        bharatNcapRating: "5 Star",
        bharatNcapChildSafetyRating: "5 Star",
      },
      adasFeatures: {
        forwardCollisionWarning: false,
        automaticEmergencyBraking: false,
        trafficSignRecognition: false,
        laneDepartureWarning: false,
        laneKeepAssist: false,
        adaptiveCruiseControl: false,
        adaptiveHighBeamAssist: false,
        blindSpotDetection: true,
        rearCrossTrafficAlert: false,
        driverAttentionMonitor: false,
        parkingAssist: false,
      },
      entertainment: {
        Radio: true,
        "Wireless Phone Charger": true,
        "Integrated 2DIN Audio": true,
        "Bluetooth Connectivity": true,
        Touchscreen: true,
        "USB Ports": true,
        "Apple Car Play": true,
        "Android Auto": true,
        "Connected Apps": true,
        "DTS Sound Staging": true,
        Tweeters: true,
        Subwoofer: true,
        touchscreenSize: 10.24,
        speakers: 4,
        speakerLocation: "Front & Rear",
        additionalEntertainmentFeatures:
          "Slim Bezel Touchscreen Infotainment System, Wireless Android Auto and Apple CarPlay",
      },
      internetFeatures: {
        eCallICall: true,
        remoteVehicleStart: true,
        sosButton: true,
        remoteACControl: true,
        geoFenceAlert: true,
      },
      images: {
        main: [
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347528566_rp6liTshg.jpg",
        ],
        interior: [
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347584552_lyv8mOJADx.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347584532_-ZVty7puh.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347584556_Jo5bT5IXE.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347584542_64tCpJGzN8.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347584547_mrp9crDXdL.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347584537_vpNgMgS1l.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347587082_riYqriba6.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347587120_6edqmeETF.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347587242_B_pb-Xu_FL.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347587518_cuNDPvYCSX.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347587526_U4ncZsCZR2.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347587522_rvP6MP16R.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347589503_nNjPvwby0.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347589505_UTBmpjj3AO.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347589759_eP0KmfBNb.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347589826_dRdWzcETR5.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347589837_17RO1Pu4XE.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347590196_3-Kr5hiP-.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347591714_oMyok9HZS.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347591760_P104kulFG.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347592008_bzYZD3q0d.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347592020_sCqER_kbN.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347592221_IJn_KMXtoV.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347592648_CVcUFD-bs.jpg",
        ],
        exterior: [
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347669921_gKJXnFSJjK.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347669906_xyCbq6GCmZ.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347669898_m20Ws_r1D.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347669918_0vT-Y9l5GD.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347669913_q7yDcEs3m-.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347669903_o6l3ecGc9.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347672096_mqKk-E6rU.jpg",
        ],
        color: [
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347305463_haeIQKJd4z.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347305481_G2QEXznKL9.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347305494_sqqSmxJFw.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347305467_wiYB6-acp.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347305478_bH6qzQ0T_.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347305489_VrgDXHTic.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347307738_C7ZpqeX5uX.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347307825_NWRLeaGpty.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347307878__sutU5bwce.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347307889_bwu2LLd6lz.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347307993_bg9CMT2GP.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347308718_Uf5nbW_n_.jpg",
          "https://ik.imagekit.io/waghDev/vehicles/upload-1743347310011_Qf7kvX1EGd.jpg",
        ],
      },
      // Use reference to the user's ID
      createdBy: new ObjectId("67d1825cf1f5573104533c39"),
      // Use current date for timestamps
      createdAt: new Date(),
      updatedAt: new Date(),
      __v: 0,
    });

    console.log(
      `\x1b[32mDocument inserted with ID:\x1b[0m ${result.insertedId}`
    );
  } catch (error) {
    console.error("\x1b[31mError during execution:\x1b[0m", error);
  } finally {
    // Close the connection
    await client.close();
    console.log("Connection closed");
  }
}

// Run the function and handle errors
run().catch((error) => {
  console.error("\x1b[31mUnhandled error:\x1b[0m", error);
});
